### PR TITLE
Fixed composer package name preventing installation.

### PR DESCRIPTION
**Pull request by Caffe1neAdd1ct**

### CODE REVIEW

**Comment by Ocramius** [comment]
@malukenho this project isn't yet tagged, no?

**Comment by malukenho** [comment]
@Ocramius Yep. No tag yet. But I'm not sure if it still valid.

**Comment by ojhaujjwal** [comment]
I am working on this [psr7-session library](https://github.com/ojhaujjwal/psr7-session) which depends on this library. A tag would be great.
but, still, I don't understand one thing. Can't I just use serialize() and deserialize()? How is it better?

Another thing, that library is probably better under this organization if it's good enough for you guys. I was just trying to do some session stuff on a `reactphp/http` and ended up writing this. It still is a work in progress though.

**Comment by Ocramius** [comment]
@ojhaujjwal the encoding/decoding is something unclear to us for now: please don't rely on this library.

As for what you linked, it doesn't seem to be related to PSR-7 at all?

**Comment by Ocramius** [comment]
Closing here meanwhile: library is not stable yet.

**Comment by ojhaujjwal** [comment]
I apologize if this is not the right place to discuss this.
It only depends on `ServerRequest::getHeaders` and `ResponseInterface::withHeader`. Maybe, I can just make it PSR-7 independent.
In any case, my motive is to create something which doesn't depend on PHP native session so that I can work with environments like `reactphp/http`

**Pull request closed without merging**
